### ISSUE TITLE
Path issue on OSX: "'julia' could not be spawned"

### ISSUE THREAD

**Issue by rdeits** [jamesdanged/Jude#1]
Thanks for putting this together; it looks really useful! Unfortunately, on OSX, I'm getting an error message when opening a new folder: 

```
'julia' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.
```

Presumably this is because I'm using julia through homebrew, so the `julia` binary is installed to `/usr/local/bin/` which is not on my default system path (and thus not on Atom's path). I'm sure I can figure out how to modify Atom's PATH variable to fix this, but you might want to consider exposing a setting for the absolute path to the `julia` binary, as [juno](https://github.com/JunoLab/atom-julia-client/tree/master/manual) does.

**Comment by rdeits** [comment]
For the record, the quick fix was to edit `~/.atom/init.coffee` and add the following line:

```
process.env.PATH += ":/usr/local/bin"
```

**Comment by jamesdanged** [comment]
Thanks. Yes being able to configure this is high on the todo list.

**Comment by jamesdanged** [comment]
This is now configurable in the options.

**Comment by rdeits** [comment]
Thanks!
