### ISSUE TITLE
Multi-line comments are not ignored

### ISSUE THREAD

**Issue by tomaklutfu** [jamesdanged/Jude#11]
Multi-line comments such as

```
#=
......
=#
```

are not ignored and gives error or warning for them.

**Comment by tomaklutfu** [comment]
No more errors with 0.2.3 update. Thanks.

**Comment by tomaklutfu** [comment]
I think it was a temporary thing that it didn't show up. Cloasing and reopenning Atom now it gives error.

**Comment by jamesdanged** [comment]
Hi, I just released a fix for this.

**Comment by tomaklutfu** [comment]
Thanks. Works now.
