### ISSUE TITLE
Union{} not parsed correctly

### ISSUE THREAD

**Issue by malmaud** [jamesdanged/Jude#12]
`Union{}` is valid syntax, but Jude reports "Unexpected end of expression". Occurs in the context of  https://github.com/JuliaWeb/Requests.jl/blob/4936215e1441aeb66d47caf05f1b011776040cb3/src/Requests.jl#L194

**Comment by jamesdanged** [comment]
This should be working now too.

**Comment by jamesdanged** [comment]
I've noticed there are still quite a few things not being parsed correctly when I load various packages authored by others. I'll work my way through the issues over time, but if there are any major issues that are bothering you the most, feel free to keep flagging them for me and I can look to them first!
