### ISSUE TITLE
String macro gives error

### ISSUE THREAD

**Issue by tomaklutfu** [jamesdanged/Jude#14]
I have something like 
``` θᵣ,ωᵣ,αᵣ=S"θᵣ",S"ωᵣ",S"αᵣ" ```
The first macro usage throws this

![screenshot from 2016-04-13 21-21-43](https://cloud.githubusercontent.com/assets/16100030/14504579/168c6e56-01be-11e6-8e4b-e150f5ccd423.png)

**Comment by jamesdanged** [comment]
Thanks. Should be fixed now.

**Comment by tomaklutfu** [comment]
Thanks that works now.
