### ISSUE TITLE
It is not an error to not have a double quote follow after include

### ISSUE THREAD

**Issue by KristofferC** [jamesdanged/Jude#17]
E.g:

![image](https://cloud.githubusercontent.com/assets/1282691/17584961/86281c02-5fb9-11e6-823a-5f420130c9ee.png)

**Comment by jamesdanged** [comment]
Sorry, this one can't be fixed. As I mention on the limitations section of the readme, Jude can only recognize string literals inside include statements. Otherwise, it would have to replicate all the Julia logic inside arbitrary functions.
