### ISSUE TITLE
Return can occur after a &&

### ISSUE THREAD

**Issue by KristofferC** [jamesdanged/Jude#19]
E.g:

![image](https://cloud.githubusercontent.com/assets/1282691/17585212/aba8aa7c-5fba-11e6-8f2c-25b7904673b5.png)

**Comment by jamesdanged** [comment]
Hi, thanks for sending in these issues! I'll put them in over the next week.

**Comment by KristofferC** [comment]
Thanks, great work with this by the way. :)

**Comment by jamesdanged** [comment]
This should be fixed in the latest release.
