### ISSUE TITLE
parse error for mapreduce?

### ISSUE THREAD

**Issue by samtkaplan** [jamesdanged/Jude#2]
Hello,

Thanks for your effort.  This package looks really promising!  I'm not sure if you are looking for bug reports or not, but here's a quick one.  Jude sees a syntax error when trying to parse a valid mapreduce call:

Atom Jude:
![atom-mapreduce](https://cloud.githubusercontent.com/assets/4575854/13928310/18d3796a-ef63-11e5-8aaa-010a0f1798cc.png)

Julia:
![julia-mapreduce](https://cloud.githubusercontent.com/assets/4575854/13928317/209a0754-ef63-11e5-8859-8d834d398acd.png)

**Comment by jamesdanged** [comment]
Thanks. I'll look into how to handle operators like that when they are function objects.

**Comment by jamesdanged** [comment]
This should be fixed in the latest release.

**Comment by samtkaplan** [comment]
Works.  Thanks for the fix!
