### ISSUE TITLE
ctrl+space remapping?

### ISSUE THREAD

**Issue by malmaud** [jamesdanged/Jude#5]
Great package - thanks for writing this. 

Is there a way to remap the ctrl-space hotkey that Jude uses? I'm already using ctrl-space for a different package.

**Comment by jamesdanged** [comment]
In Settings -> Keybindings, you should see that `autocomplete-plus:activate` is bound to `ctrl-space`. It says you can override it in your keymap.cson file. I just tried the following in mine, and now both `ctrl-space` and `ctrl-shift-J` work. So maybe you can set up overrides that maps autocomplete+ to something and your own package to `ctrl-space`.

    'atom-text-editor':
      'ctrl-shift-J': 'autocomplete-plus:activate'

**Comment by malmaud** [comment]
Thanks!
