### ISSUE TITLE
Parsing not happening automatically

### ISSUE THREAD

**Issue by malmaud** [jamesdanged/Jude#6]
Parsing isn't happening as I type - I have to explicitly trigger it by saving the buffer or running `reparse all`.

**Comment by jamesdanged** [comment]
I noticed that this sometimes happens at startup. Switching back and forth between multiple open tabs can help. If the file tree at the left is open, it seems to interfere too. Let me know if that helps.

**Comment by jamesdanged** [comment]
Let me know if this is still happening, or I can close this. Thanks.

**Comment by malmaud** [comment]
It does seem to work now, thanks.
