### ISSUE TITLE
Conflict with latex-completions?

### ISSUE THREAD

**Issue by dpo** [jamesdanged/Jude#7]
This is an excellent package but I'm experiencing conflicts with `latex-completions`. Disabling `jude` enables `latex-completions` again.  I'm on OSX, Atom 1.6.0, Jude 0.2.0, LaTeX Completions 0.3.1.

**Comment by jamesdanged** [comment]
Ah, ok, Jude is blocking other autocompleters. I'll set it so it doesn't block them.

**Comment by dpo** [comment]
Thanks!

**Comment by jamesdanged** [comment]
Ok, the latest update should fix this. You can configure how Jude interacts with other autocompleters in the settings too.
