### ISSUE TITLE
jump to declaration doesn't seem to work for me

### ISSUE THREAD

**Issue by LeoK987** [jamesdanged/Jude#8]
Not sure what is wrong with my setting, but Ctrl-Space does not do anything when the cursor is on a function name.  I am on Ubuntu 64bits with Atom 1.6.0.

Also, does this package interfere with autocomplete-julia?

**Comment by jamesdanged** [comment]
Hi, what other packages do you have installed? Does any autocomplete work as you type? Does ctrl-space work on functions like println? Is `julia` on your path? You can open the chromium dev tools `Window: Toggle Dev Tools` and look at any errors reported in the console.

Also, the latest update allows you to configure in the settings how Jude interacts with other autocompleters, so it shouldn't interfere any more with autocomplete-julia.

**Comment by LeoK987** [comment]
On Tuesday, March 29, 2016, James Dang <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Hi, what other packages do you have installed?
>
I have 10 community packages and 75 core packages (were they installed by
default).  Included is autocomplete-julia.  Besides autocomplete-julia,
there are a bunch of autocomplete core packages.  (how can I easily copy
and paste the list of packages?)

> Does any autocomplete work as you type?
>
Yes, autocomplete works in some way.  I just tested by disabling
autocomplete-julia and jude, autocomplete still works.  So I have no idea
what happens.

> Does ctrl-space work on functions like println?
>
 With jude and autocomplete-julia disabled, ctrl-space on a function
(println) brings up a list of choices, and if I select one from the list
the function name gets replaced with the selected item.  With jude or
autocomplete-julia enabled, the behavior is the same.

> Is julia on your path?
>
Yes, I can run 'julia' in the terminal.

> You can open the chromium dev tools Window: Toggle Dev Tools and look at
> any errors reported in the console.
>
I currently don't have chromium installed.

> Also, the latest update allows you to configure in the settings how Jude
> interacts with other autocompleters, so it shouldn't interfere any more
> with autocomplete-julia.
>
The above is about the latest update of all packages.

**Comment by LeoK987** [comment]
I appears the package at work is language-julia.  If I disable it, then
autocompletion does not work.  But language-julia package is quite
essential to julia, isn't it?

**Comment by jamesdanged** [comment]
Yes, language-julia is required. I should have documented it before on the readme. I just made changes so that both `linter` and `language-julia` are forced to be installed. If they are not installed, the text you see in a julia file won't even be syntax colored. Was that the problem? 

Atom actually has many autocomplete providing packages, so it's likely you were getting autocomplete results from some other packages, such as perhaps `julia-client`. 

The dev tools I was referring to are built into Atom. Just press ctrl-shift-p (or cmd-shift-p on mac) and type `Window Toggle Dev Tools` to open it. If you are still having issues, let me know what you see in the console there.

**Comment by LeoK987** [comment]
I just updated jude, and found that it automatically installed package
linter which I didn't have.

Then I restarted atom, and in the console appeared a bunch of messages
seemingly coming from jude (I pasted them to the bottom).

Then I did ctrl-space on println.  Same as yesterday, I got a pop window
(screenshot of which is attached).  If I select println, the cursor simply
goes to the end of the text of "println".  If I select other text, the text
would simply replace "println".  Doing ctrl-space on my own functions
behaved similarly.

The message for ctrl-space in the console is:
JumpController.ts:60 Must select an identifier.

btw, I do not have julia-client installed.


-------------------------
Reparsing all files.
2/home/xxx/.atom/packages/Jude/dist/core/JumpController.js:55 Must select
an identifier.
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131 Module
'DataFrames' should be in the workspace at
/home/xxx/.julia/v0.4/DataFrames/src/DataFrames.jl but the file did not
declare a module with name 'DataFrames'.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131 Module
'TimeSeries' should be in the workspace at
/home/xxx/.julia/v0.4/TimeSeries/src/TimeSeries.jl but the file did not
declare a module with name 'TimeSeries'.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131 Module
'ArrayViews' should be in the workspace at
/home/xxx/.julia/v0.4/ArrayViews/src/ArrayViews.jl but the file did not
declare a module with name 'ArrayViews'.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131 Module
'Compat' should be in the workspace at
/home/xxx/.julia/v0.4/Compat/src/Compat.jl but the file did not declare a
module with name 'Compat'.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131 Module 'Cairo'
should be in the workspace at /home/xxx/.julia/v0.4/Cairo/src/Cairo.jl but
the file did not declare a module with name 'Cairo'.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108 Module
'HttpParser' was not found in the file system.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108 Module
'ColorBrewer' was not found in the file system.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108 Module 'JLD'
was not found in the file system.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131 Module
'DataArrays' should be in the workspace at
/home/xxx/.julia/v0.4/DataArrays/src/DataArrays.jl but the file did not
declare a module with name 'DataArrays'.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108 Module
'Benchmark' was not found in the file system.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108 Module
'Lapidary' was not found in the file system.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131 Module
'Docile' should be in the workspace at
/home/xxx/.julia/v0.4/Docile/src/Docile.jl but the file did not declare a
module with name 'Docile'.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108 Module
'Lexicon' was not found in the file system.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108 Module
'FactCheck' was not found in the file system.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131 Module
'Graphics' should be in the workspace at
/home/xxx/.julia/v0.4/Graphics/src/Graphics.jl but the file did not declare
a module with name 'Graphics'.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108 Module
'BenchmarkLite' was not found in the file system.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131 Module
'StatsFuns' should be in the workspace at
/home/xxx/.julia/v0.4/StatsFuns/src/StatsFuns.jl but the file did not
declare a module with name 'StatsFuns'.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108 Module 'GLM'
was not found in the file system.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131 Module 'Tk'
should be in the workspace at /home/xxx/.julia/v0.4/Tk/src/Tk.jl but the
file did not declare a module with name 'Tk'.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:131
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108 Module 'Gtk'
was not found in the file system.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108 Module
'Morsel' was not found in the file system.(anonymous function) @
/home/xxx/.atom/packages/Jude/dist/core/ModuleLibrary.js:108
/home/xxx/.atom/packages/Jude/dist/nameResolution/ScopeBuilder.js:246
Uncaught (in promise) TypeError: Cannot read property 'token' of null(…)
/home/xxx/.atom/packages/Jude/dist/core/JumpController.js:55 Must select an
identifier.

**Comment by jamesdanged** [comment]
Ok, I see the same problems you see when I load my entire directory of julia modules. I've put in a few fixes and better error handling in the latest release. Hopefully, the package should fully parse your workspace now. Let me know if it is still not working.

Also, if you load the whole directory of built in and downloaded modules, it will take quite a few minutes to do the initial parsing. There's no animated indicator yet to tell you it is busy running.

There will be parsing errors for many of the typical julia packages. Like I say on the readme, there are gaps in what the parser can handle so far. If there's a parsing problem in a file, it may not resolve any names below the line with the parsing error. You'll get a better sense of if things are working or not if you just create a new empty file with the line `println("Hello world")` and try pressing `ctrl-space` on the `println`.

**Comment by LeoK987** [comment]
Yes, the new version appears working.  Thanks.

Is there a way to not show error or warning messages at the bottom of
editor?  I current see the following for instance, and the reported cases
do not seem to be problems.

Julia
Error
Unexpected symbolat line 157 col 15
Julia
Error
Unexpected symbolat line 258 col 23
Julia
Error
Unexpected symbolat line 481 col 27
Julia
Error
Unexpected symbolat line 862 col 19
Julia
Error
Unexpected symbolat line 992 col 27
Julia
Warning
'SkipTrades' already declared in this scope.at line 12 col 7
Julia
Warning
Unknown nameat line 26 col 14

**Comment by LeoK987** [comment]
Sorry, no worries about not showing error messages.  I see that I can click
on either "File" or "Project" icons at the bottom to hide them.
